// <auto-generated />
using System;
using Kiosco.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiosco.Infrastructure.Migrations
{
    [DbContext(typeof(KioscoDbContext))]
    [Migration("20260913230009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiosco.Domain.Entities.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abierta")
                        .HasColumnType("boolean");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.DetalleIngresoMercaderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngresoMercaderiaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngresoMercaderiaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesIngresoMercaderia");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.IngresoMercaderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("IngresosMercaderia");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CajaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "usuarios.gestionar",
                            Descripcion = "Crear, editar y deshabilitar usuarios",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "roles.gestionar",
                            Descripcion = "Asignar roles y permisos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Roles"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "productos.crear",
                            Descripcion = "Registrar nuevos productos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Crear Productos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "productos.editar",
                            Descripcion = "Modificar información de productos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Editar Productos"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "productos.eliminar",
                            Descripcion = "Deshabilitar productos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Eliminar Productos"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "productos.consultar",
                            Descripcion = "Ver catálogo de productos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Consultar Productos"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Codigo = "ventas.crear",
                            Descripcion = "Registrar nuevas ventas",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Crear Ventas"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Codigo = "ventas.consultar",
                            Descripcion = "Ver historial de ventas",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Consultar Ventas"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Codigo = "ventas.anular",
                            Descripcion = "Anular ventas registradas",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Anular Ventas"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Codigo = "caja.abrir",
                            Descripcion = "Registrar apertura de caja",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Abrir Caja"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Codigo = "caja.cerrar",
                            Descripcion = "Registrar cierre de caja",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cerrar Caja"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Codigo = "caja.movimientos",
                            Descripcion = "Registrar ingresos y egresos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Movimientos de Caja"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Codigo = "informes.consultar",
                            Descripcion = "Ver reportes e informes",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Consultar Informes"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Codigo = "informes.exportar",
                            Descripcion = "Exportar reportes a Excel",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Exportar Informes"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Codigo = "stock.gestionar",
                            Descripcion = "Administrar inventario",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Stock"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Codigo = "proveedores.gestionar",
                            Descripcion = "Administrar proveedores",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Proveedores"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Codigo = "clientes.gestionar",
                            Descripcion = "Administrar clientes",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Clientes"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Codigo = "rubros.gestionar",
                            Descripcion = "Crear y editar rubros",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestionar Rubros"
                        });
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("RubroId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cuit")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Acceso total al sistema",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Gestión de operaciones y reportes",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Operador Administrativo"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Operaciones básicas de venta",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 18
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 18
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 13
                        });
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Rubros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Bombones, chocolates, caramelos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Golosinas"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Gaseosas, jugos, aguas, energizantes",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Papas fritas, maní, palitos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Snacks"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Aceites, harinas, conservas",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Almacén"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Leche, yogur, quesos",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lácteos"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Jabón, detergente, lavandina",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Productos varios",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Sistema",
                            Email = "admin@kiosco.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseUid = "ADMIN_FIREBASE_UID_CAMBIAR",
                            Nombre = "Admin",
                            NombreUsuario = "admin",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Caja", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Usuario", "UsuarioApertura")
                        .WithMany()
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.DetalleIngresoMercaderia", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.IngresoMercaderia", "IngresoMercaderia")
                        .WithMany("Detalles")
                        .HasForeignKey("IngresoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesIngreso")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngresoMercaderia");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.IngresoMercaderia", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("IngresosMercaderia")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Caja", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Venta", "Venta")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("Kiosco.Domain.Entities.MovimientoCaja", "VentaId");

                    b.Navigation("Caja");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Rubro", "Rubro")
                        .WithMany("Productos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosco.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Stock", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Producto", "Producto")
                        .WithOne("Stock")
                        .HasForeignKey("Kiosco.Domain.Entities.Stock", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Venta", b =>
                {
                    b.HasOne("Kiosco.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("Kiosco.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Caja", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.IngresoMercaderia", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesIngreso");

                    b.Navigation("DetallesVenta");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("IngresosMercaderia");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Rubro", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MovimientosCaja");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Kiosco.Domain.Entities.Venta", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("MovimientoCaja");
                });
#pragma warning restore 612, 618
        }
    }
}
